### ISSUE TITLE
[FEATURE][DBCreate] 임시 DB 생성하기

### ISSUE THREAD

**Issue by jinvvoo** [chain-smoker/Marronnier#146]
## Description
임시용으로 사용할 수 있도록 DB를 몇 개 추가한다. 
칵테일 레시피 (cocktailrecipe_tb)
재료 레시피 (element_tb)
재료와레시피 (elementbyrecipe_tb)

각 테이블을 채워준다.

---

## TODO
- [x]  칵테일 레시피에 들어갈 내용을 추가한다
- [x]  재료 레시피에 들어갈 내용을 추가한다. 
- [x]  재료와레시피에 들어갈 내용을 추가한다.

---

## ETC

---
