### ISSUE TITLE
[FEATURE][COCKTAIL] 칵테일 등록 기능 

### ISSUE THREAD

**Issue by CodeJugller** [chain-smoker/Marronnier#20]
## Description
새로운 기능 추가에 관련 된 이슈 템플릿입니다.

---

## TODO
- [x] CocktailRecipe(칵테일 조주법) 등록 기능(관리자)
- [ ] Element(칵테일 재료) 등록 기능(관리자)
- [ ]  칵테일 재료 및 조주법 입력을 통한 등록 기능(관리자 및 유저)

---

## ETC

---
각각 기능을 시연하기 위한 간단한 페이지도 작성
