### ISSUE TITLE
[FEATURE][AUTH] 인증, 인가에 따른 에러 페이지 처리

### ISSUE THREAD

**Issue by jiwon11** [chain-smoker/Marronnier#92]
## Description
새로운 기능 추가에 관련 된 이슈 템플릿입니다.

---

## TODO
- [x]  SecurityConfiguration 클래스에서 authenticationEntryPoint와 accessDeniedHandler 수정
- [x] main domain 패키지 생성
- [x] main domain 패키지에서 ErrorController 클래스 생성
- [x] resources 에 main 폴더 생성 후 error html 생성

---

## ETC

---
* 없음
