### ISSUE TITLE
[FEATURE][PHOTO] 사진 업로드

### ISSUE THREAD

**Issue by jiwon11** [chain-smoker/Marronnier#94]
---

## Description
새로운 기능 추가에 관련 된 이슈 템플릿입니다.

---

## TODO
- [ ] Photo 엔티티 생성
- [ ] Photo 엔티티와 타 엔티티 간의 중간 객체 생성 
- [ ] Spring boot를 통한 사진 업로드

---

## ETC

---
* 없음
